/* Generated by Yosys 0.56+30 (git sha1 2d90e80b5, g++ 11.4.0-1ubuntu1~22.04 -fPIC -O3) */

module alu_with_mux(A, B, select, result);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  input [1:0] select;
  wire [1:0] select;
  output [3:0] result;
  wire [3:0] result;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire [3:0] and_result;
  wire [3:0] difference;
  wire [3:0] or_result;
  wire [3:0] sum;
  INV_X1 _17_ (
    .A(A[2]),
    .ZN(_00_)
  );
  INV_X1 _18_ (
    .A(A[1]),
    .ZN(_01_)
  );
  INV_X1 _19_ (
    .A(A[0]),
    .ZN(_02_)
  );
  OR2_X1 _20_ (
    .A1(B[3]),
    .A2(A[3]),
    .ZN(or_result[3])
  );
  AND2_X1 _21_ (
    .A1(B[3]),
    .A2(A[3]),
    .ZN(and_result[3])
  );
  XOR2_X1 _22_ (
    .A(B[3]),
    .B(A[3]),
    .Z(_03_)
  );
  OR2_X1 _23_ (
    .A1(B[2]),
    .A2(A[2]),
    .ZN(or_result[2])
  );
  AND2_X1 _24_ (
    .A1(B[2]),
    .A2(A[2]),
    .ZN(and_result[2])
  );
  XNOR2_X1 _25_ (
    .A(B[2]),
    .B(A[2]),
    .ZN(_04_)
  );
  NOR2_X1 _26_ (
    .A1(B[1]),
    .A2(_01_),
    .ZN(_05_)
  );
  OR2_X1 _27_ (
    .A1(B[1]),
    .A2(A[1]),
    .ZN(or_result[1])
  );
  NAND2_X1 _28_ (
    .A1(B[1]),
    .A2(A[1]),
    .ZN(_06_)
  );
  INV_X1 _29_ (
    .A(_06_),
    .ZN(and_result[1])
  );
  XOR2_X1 _30_ (
    .A(B[1]),
    .B(A[1]),
    .Z(_07_)
  );
  OR2_X1 _31_ (
    .A1(B[0]),
    .A2(A[0]),
    .ZN(or_result[0])
  );
  AND2_X1 _32_ (
    .A1(B[0]),
    .A2(A[0]),
    .ZN(and_result[0])
  );
  XOR2_X1 _33_ (
    .A(B[0]),
    .B(A[0]),
    .Z(difference[0])
  );
  AOI21_X1 _34_ (
    .A(_07_),
    .B1(_02_),
    .B2(B[0]),
    .ZN(_08_)
  );
  NOR2_X1 _35_ (
    .A1(_05_),
    .A2(_08_),
    .ZN(_09_)
  );
  OAI21_X1 _36_ (
    .A(_04_),
    .B1(_05_),
    .B2(_08_),
    .ZN(_10_)
  );
  OAI21_X1 _37_ (
    .A(_10_),
    .B1(_00_),
    .B2(B[2]),
    .ZN(_11_)
  );
  XNOR2_X1 _38_ (
    .A(_03_),
    .B(_11_),
    .ZN(difference[3])
  );
  XNOR2_X1 _39_ (
    .A(_04_),
    .B(_09_),
    .ZN(difference[2])
  );
  AND3_X1 _40_ (
    .A1(B[0]),
    .A2(_02_),
    .A3(_07_),
    .ZN(_12_)
  );
  NOR2_X1 _41_ (
    .A1(_08_),
    .A2(_12_),
    .ZN(difference[1])
  );
  NAND2_X1 _42_ (
    .A1(_07_),
    .A2(and_result[0]),
    .ZN(_13_)
  );
  AOI21_X1 _43_ (
    .A(_04_),
    .B1(_06_),
    .B2(_13_),
    .ZN(_14_)
  );
  NOR2_X1 _44_ (
    .A1(and_result[2]),
    .A2(_14_),
    .ZN(_15_)
  );
  XNOR2_X1 _45_ (
    .A(_03_),
    .B(_15_),
    .ZN(sum[3])
  );
  AND3_X1 _46_ (
    .A1(_04_),
    .A2(_06_),
    .A3(_13_),
    .ZN(_16_)
  );
  NOR2_X1 _47_ (
    .A1(_14_),
    .A2(_16_),
    .ZN(sum[2])
  );
  XOR2_X1 _48_ (
    .A(_07_),
    .B(and_result[0]),
    .Z(sum[1])
  );
  XOR2_X1 _49_ (
    .A(B[0]),
    .B(A[0]),
    .Z(sum[0])
  );
  mux_4_to_1 mux_inst (
    .in0(sum),
    .in1(difference),
    .in2(and_result),
    .in3(or_result),
    .out(result),
    .sel(select)
  );
endmodule

module mux_4_to_1(in0, in1, in2, in3, sel, out);
  input [3:0] in0;
  wire [3:0] in0;
  input [3:0] in1;
  wire [3:0] in1;
  input [3:0] in2;
  wire [3:0] in2;
  input [3:0] in3;
  wire [3:0] in3;
  input [1:0] sel;
  wire [1:0] sel;
  output [3:0] out;
  wire [3:0] out;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  INV_X1 _19_ (
    .A(sel[0]),
    .ZN(_00_)
  );
  INV_X1 _20_ (
    .A(sel[1]),
    .ZN(_01_)
  );
  NAND3_X1 _21_ (
    .A1(in2[2]),
    .A2(_00_),
    .A3(sel[1]),
    .ZN(_02_)
  );
  NOR2_X1 _22_ (
    .A1(sel[0]),
    .A2(sel[1]),
    .ZN(_03_)
  );
  NAND2_X1 _23_ (
    .A1(in0[2]),
    .A2(_03_),
    .ZN(_04_)
  );
  NAND3_X1 _24_ (
    .A1(in1[2]),
    .A2(sel[0]),
    .A3(_01_),
    .ZN(_05_)
  );
  NAND3_X1 _25_ (
    .A1(in3[2]),
    .A2(sel[0]),
    .A3(sel[1]),
    .ZN(_06_)
  );
  NAND4_X1 _26_ (
    .A1(_02_),
    .A2(_04_),
    .A3(_05_),
    .A4(_06_),
    .ZN(out[2])
  );
  NAND2_X1 _27_ (
    .A1(in0[1]),
    .A2(_03_),
    .ZN(_07_)
  );
  NAND3_X1 _28_ (
    .A1(in2[1]),
    .A2(_00_),
    .A3(sel[1]),
    .ZN(_08_)
  );
  NAND3_X1 _29_ (
    .A1(in3[1]),
    .A2(sel[0]),
    .A3(sel[1]),
    .ZN(_09_)
  );
  NAND3_X1 _30_ (
    .A1(in1[1]),
    .A2(sel[0]),
    .A3(_01_),
    .ZN(_10_)
  );
  NAND4_X1 _31_ (
    .A1(_07_),
    .A2(_08_),
    .A3(_09_),
    .A4(_10_),
    .ZN(out[1])
  );
  NAND3_X1 _32_ (
    .A1(in3[0]),
    .A2(sel[0]),
    .A3(sel[1]),
    .ZN(_11_)
  );
  NAND3_X1 _33_ (
    .A1(in2[0]),
    .A2(_00_),
    .A3(sel[1]),
    .ZN(_12_)
  );
  NAND3_X1 _34_ (
    .A1(in1[0]),
    .A2(sel[0]),
    .A3(_01_),
    .ZN(_13_)
  );
  NAND2_X1 _35_ (
    .A1(in0[0]),
    .A2(_03_),
    .ZN(_14_)
  );
  NAND4_X1 _36_ (
    .A1(_11_),
    .A2(_12_),
    .A3(_13_),
    .A4(_14_),
    .ZN(out[0])
  );
  NAND3_X1 _37_ (
    .A1(sel[0]),
    .A2(sel[1]),
    .A3(in3[3]),
    .ZN(_15_)
  );
  NAND3_X1 _38_ (
    .A1(_00_),
    .A2(sel[1]),
    .A3(in2[3]),
    .ZN(_16_)
  );
  NAND2_X1 _39_ (
    .A1(in0[3]),
    .A2(_03_),
    .ZN(_17_)
  );
  NAND3_X1 _40_ (
    .A1(sel[0]),
    .A2(_01_),
    .A3(in1[3]),
    .ZN(_18_)
  );
  NAND4_X1 _41_ (
    .A1(_15_),
    .A2(_16_),
    .A3(_17_),
    .A4(_18_),
    .ZN(out[3])
  );
endmodule
